#server:
#   port: 8083
#spring:
#  application:
#    name: search-service
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.56.101:9300
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#    registry-fetch-interval-sercond: 5
#  instance:
#    prefer-ip-adress: true
#    ip-adress: 127.0.0.1
server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.192.136:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.192.136
    username: leyou
    password: leyou
    virtual-host: /leyou
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    #    写iP防止别人拿到的是主机名
#    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

ribbon:
  eureka:
    enable: true

